### ISSUE TITLE
示例描述有点问题

### ISSUE THREAD

**Issue by chenlei0608** [wangdoc/typescript-tutorial#110]
![Snipaste_2024-06-26_21-19-28](https://github.com/wangdoc/typescript-tutorial/assets/172103606/56152ead-0c21-4ad0-ab41-6e52b2d3b889)

泛型一章，红色实线画出的一句貌似有点问题吧。参数数组和返回值不是一个类型，只是类型有一定关系。

**Comment by ruanyf** [comment]
TypeScript 数组成员是同类型的。
