### ISSUE TITLE
"d.ts 类型声明文件" 章节链接错误

### ISSUE THREAD

**Issue by Charles47-wc** [wangdoc/typescript-tutorial#112]
"d.ts 类型声明文件" 章节链接错误
应当为：https://typescript.p6p.net/typescript-tutorial/d.ts.html
实际为：https://typescript.p6p.net/typescript-tutorial/d.ts
导致 404 错误

**Comment by ruanyf** [comment]
p6p  与官网无关，是网友自己架设的。
