### ISSUE TITLE
文档代码片段 编写有误

### ISSUE THREAD

**Issue by XiaoLiz** [wangdoc/typescript-tutorial#118]
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/a4f20c5d-c6a9-47ab-b252-bd85a2f153cd">

链接： https://typescript.p6p.net/typescript-tutorial/object.html

`
// 属性类型以分号结尾
type MyObj = {
  x: number;
  y: number;
};

// 属性类型以逗号结尾
type MyObj = {
  x: number,
  y: number,
};`

**Comment by ruanyf** [comment]
能不能问一下，你是从哪里知道 p6p.net 有这个教程的？

他们不是官方的平台，并且私自改动了文档内容，还改错了。

正确和更新的内容，都要以网道项目为准。https://wangdoc.com/typescript/object#%E7%AE%80%E4%BB%8B
