### ISSUE TITLE
这里应该是都可以吧，不一定是最后一个属性吧

### ISSUE THREAD

**Issue by coderwhytop** [wangdoc/typescript-tutorial#120]
![image](https://github.com/user-attachments/assets/0a8053d1-412c-4f6a-955d-80a9976b9fc3)
![image](https://github.com/user-attachments/assets/9629411d-cd44-40d1-afd3-bc05aecf4c97)

**Comment by coderwhytop** [comment]
只是不规范的话可以说明不规范，不然语境上以为是必须这么写，有歧义的

**Comment by ruanyf** [comment]
原文无歧义
