### ISSUE TITLE
第14章节的第4小结讲到class Point {     x:number; // 报错     y!:number; // 正确      constructor(x:number, y:number) {         // ...     } } 应该是ts5.0之前的版本吧

### ISSUE THREAD

**Issue by coderwhytop** [wangdoc/typescript-tutorial#121]
![image](https://github.com/user-attachments/assets/97bfcbb7-c1c7-42fc-9f43-a1640c2ddcac)
![image](https://github.com/user-attachments/assets/ed2d67f2-4e24-4ebb-b82c-e7a061c341e3)

**Comment by ruanyf** [comment]
TS 官网 playground 为准。
