### ISSUE TITLE
小纠错

### ISSUE THREAD

**Issue by bigcake008** [wangdoc/typescript-tutorial#124]
[https://github.com/wangdoc/javascript-tutorial/issues/url](url)

> 上面示例中，{}代表了 Object 类型，不打开strictNullChecks时，它包括了undefined和null，就相当于包括了所有类型的值，所以这时unknown类型可以赋值给{}类型，类型A就为number。打开strictNullChecks时，{}就排除掉了undefined和null，这时unknown类型就不能赋值给{}类型后，类型A就为string。

阮老师，这里类型A的判定写反了。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
