### ISSUE TITLE
关于 21章节 第4小节 extends... ? : 的疑问，貌似有问题

### ISSUE THREAD

**Issue by coderwhytop** [wangdoc/typescript-tutorial#125]
![f6d44b22a90ddf0f915beff31fd5656](https://github.com/user-attachments/assets/ca9bff01-b9b0-4e65-9e5b-336898a1391a)
你好，按照这里说的，type Z = ('x' | 1) extends (string | boolean) ? 'x' : 1; 分解为 ('x' extends string | boolean ? 'x' : 1) | (1 extends string | boolean ? 'x' : 1)， 岂不是 返回 'x' | 1 了 ？

**Comment by ruanyf** [comment]
谢谢指出，已经更正。

正确说法是这个只对泛型有效。

```
type T1 = 'x' | 1;
type T2<T> = T extends (string | boolean) ? 'x' : 1;
type T3 = T2<T1>; // 'x' | 1
```
