### ISSUE TITLE
数组章节-数组的类型推断问题

### ISSUE THREAD

**Issue by leejunhui** [wangdoc/typescript-tutorial#18]
```typescript
// 推断为 any[]
const arr = [];

// 推断类型为 number[]
arr.push(123);

// 推断类型为 (string | number)[]
arr.push('abc');
```
[数组的类型推断 - 网道](https://wangdoc.com/typescript/array#%E6%95%B0%E7%BB%84%E7%9A%84%E7%B1%BB%E5%9E%8B%E6%8E%A8%E6%96%AD)
如上所示，在 ts playground 和 vscode 中测试，`arr` 在添加了 `number` 和 `string` 之后，仍然被推断为 `any[]`。

**Comment by ruanyf** [comment]
试试下面的代码

```typescript
let arr = [];
arr // 推断为 any[]

arr.push(123);
arr // 推断类型为 number[]

arr.push('abc');
arr // 推断类型为 (string | number)[]
```

**Comment by leejunhui** [comment]
> 试试下面的代码
> 
> ```ts
> let arr = [];
> arr // 推断为 any[]
> 
> arr.push(123);
> arr // 推断类型为 number[]
> 
> arr.push('abc');
> arr // 推断类型为 (string | number)[]
> ```

是的，直接在 `arr.push` 语句上去查看 `arr` 的类型还是 `any[]`，但是后面再去使用 `arr` 的时候类型已经变了😄
