### ISSUE TITLE
第15章模块

### ISSUE THREAD

**Issue by EthanLiu2022** [wangdoc/typescript-tutorial#31]
第15章模块中简介章有语言描述错误。
![image](https://github.com/wangdoc/typescript-tutorial/assets/49427072/21ca0242-3db0-4b04-8cbf-68aacf7f9ac5)
这里应该改为：
上面命令发现b.ts依赖a.ts，就会自动寻找a.ts，也将其同时编译，因此编译产物还是a.js和b.js两个文件。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
