### ISSUE TITLE
對象：最小可选属性规则一節問題

### ISSUE THREAD

**Issue by Sayoko123f** [wangdoc/typescript-tutorial#37]
[文件連結](https://wangdoc.com/typescript/object#%E6%9C%80%E5%B0%8F%E5%8F%AF%E9%80%89%E5%B1%9E%E6%80%A7%E8%A7%84%E5%88%99)

## 原文

如果一个对象的所有属性都是可选的，会触发最小可选属性规则。

```ts
type Options = {
  a?:number;
  b?:number;
  c?:number;
};

const obj:Options = {
  d: 123 // 报错
};
```

上面示例中，类型Options是一个对象，它的所有属性都是可选的，这导致任何对象实际都符合Options类型。

为了避免这种情况，TypeScript 添加了最小可选属性规则，规定这时属于Options类型的对象，必须至少存在一个可选属性，不能所有可选属性都不存在。这就是为什么上例的myObj对象会报错的原因。

## 問題描述

原文示例會報錯的原因是 d 不存在於 Options 類型中，並不是因為 最小可选属性规则

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AzlAvFA3gKCkKgEMB+ALihQFcBbAIwgCcBuAo+iqux19wgMZcaDZmwC+bPHgD0MqICSbQJDmgemTAJVF4BqNMChJ6AKwCMlOIm1Zc46QBMIAgDbEm0AGbUUA8yihhnaCDNkFAAKJHhgtFMI7QBKSgA3JAQbaTkoQFm5QDZHQEYNFTw-JgCg1BCcEkojABooG0qocVjpWXlldQL-QJjQnEagA)

```ts
type Options = {
    a?: number;
    b?: number;
    c?: number;
};


// 沒有錯誤
const obj1: Options = {}

declare function parseOption(options: Options): void

// 仍然報錯
parseOption({ a: 1, d: 1 })


// 沒有錯誤
parseOption({})
```

**Comment by ruanyf** [comment]
我改了一下，详见官方文档 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#weak-type-detection
