### ISSUE TITLE
👑 [建议] 导航菜单栏的优化

### ISSUE THREAD

**Issue by LiMao00** [wangdoc/typescript-tutorial#4]
### 🥰 需求描述 | Requirements description
当前菜单栏的部分不太方便，阅读到底部想切换想要的栏目还需拖回顶部。当然，是有点吹毛求疵了。不过我个人蛮重视有户体验的，仅作为建议。

### 🧐 解决方案 | Solution
类似 https://vitepress.dev/guide/what-is-vitepress ，左侧大栏目，右侧当前页的小标题（应该是当前最流行的 markdown 类布局，条理清晰）

### 🚑 其他信息 | Other information
ps：只是建议，如果改进了，万分感谢。还有搜索方案很棒。

**Comment by vannvan** [comment]
> ### 🥰 需求描述 | Requirements description
> 当前菜单栏的部分不太方便，阅读到底部想切换想要的栏目还需拖回顶部。当然，是有点吹毛求疵了。不过我个人蛮重视有户体验的，仅作为建议。
> 
> ### 🧐 解决方案 | Solution
> 类似 https://vitepress.dev/guide/what-is-vitepress ，左侧大栏目，右侧当前页的小标题（应该是当前最流行的 markdown 类布局，条理清晰）
> 
> ### 🚑 其他信息 | Other information
> ps：只是建议，如果改进了，万分感谢。还有搜索方案很棒。

哇，刚想来提，结果不谋而合哈哈哈

**Comment by ruanyf** [comment]
鼠标悬停在章节标题，会出现“返回上部”按钮。

关于粘性菜单栏，目前暂时不提供，以后全站改版的时候会考虑。

**Comment by nabaonan** [comment]
右侧锚点确实不太实用，希望可以吸顶
