### ISSUE TITLE
注释指令 // @ts-expect-error 描述問題

### ISSUE THREAD

**Issue by Sayoko123f** [wangdoc/typescript-tutorial#41]
## 原文

// @ts-ignore或// @ts-expect-error，告诉编译器不对下一行代码进行类型检查，可以用于 TypeScript 脚本，也可以用于 JavaScript 脚本。

## 問題描述

[文件說明](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments)

@ts-ignore 和 @ts-expect-error 的用法並不相同

如果 // @ts-expect-error 下一行沒有錯誤，那麼在註釋行會出現錯誤
```
Unused '@ts-expect-error' directive.
```

**Comment by Sayoko123f** [comment]
額外建議補充：

可以增加 // ^? 指令的說明，在 TS Playground 或 VS Code 編輯器都有效

**Comment by ruanyf** [comment]
`// @ts-expect-error ` 已经改正了。

至于`//^?`，那个只是编辑器辅助显示功能，对代码没有影响。
