### ISSUE TITLE
第13章《Enum 类型》第3小节最后一段示例代码有个笔误

### ISSUE THREAD

**Issue by sciencefunq** [wangdoc/typescript-tutorial#45]
![fix1](https://github.com/wangdoc/typescript-tutorial/assets/102168820/6c99ae69-8433-40ac-ae4b-84491159faf7)

如图，根据上下文，这里const Enum E2 是否应该修改为 const Enum E

**Comment by ruanyf** [comment]
谢谢指出，已经更正。https://github.com/wangdoc/typescript-tutorial/commit/39891fe0abaa32955a419cdca286c85abc906142
