### ISSUE TITLE
Symbol 包装类型的问题？

### ISSUE THREAD

**Issue by aiyadingya** [wangdoc/typescript-tutorial#56]
`const sym1:symbol = Object(Symbol('tset'))`

我发现这样写，并没有报错。但按文档而言，这样获取的是包装类型，小写的symbol类型是不正确的？这里是不是有问题

**Comment by ruanyf** [comment]
理论上，symbol 和 Symbol 应该是两个不同类型。但是，目前在 TypeScript 里面它们没有差异。

我没有查到原因，不确定是不是官方的疏忽。

BigInt 也有这个问题。
