### ISSUE TITLE
第11章类第8节抽象类，抽象成员部分关于抽象方法那里应该是笔误

### ISSUE THREAD

**Issue by jinsest** [wangdoc/typescript-tutorial#59]
第11章类第8节抽象类，抽象成员部分关于抽象方法那里“如果抽象类的属性前面加上abstract，就表明子类必须给出该方法的实现。“应该是”如果抽象类的方法前面加上abstract，就表明子类必须给出该方法的实现。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
