### ISSUE TITLE
建议页面上左侧目录，和每个章节的目录，在页面滚动的时候，可以始终在可视区域可见，便于随时切换

### ISSUE THREAD

**Issue by deyinliu** [wangdoc/typescript-tutorial#73]

**Comment by wbc0301** [comment]
这个建议不错

**Comment by leinad59** [comment]
同 https://github.com/wangdoc/typescript-tutorial/issues/4

**Comment by ruanyf** [comment]
最近不会改动页面布局，开发重点还是放在增加内容。

鼠标悬停在章节标题，会出现向上按钮。

**Comment by flyMDW** [comment]
我的解决方案：chrome搜索浏览器插件 Smart TOC。 插件可以实现当前页面目录固定。

**Comment by wbc0301** [comment]
> 最近不会改动页面布局，开发重点还是放在增加内容。
> 
> 鼠标悬停在章节标题，会出现向上按钮。

嗯嗯  还是很感谢阮老师的文档，已经很不错了。
