### ISSUE TITLE
关于 模块—简介 部分

### ISSUE THREAD

**Issue by CaiSijian** [wangdoc/typescript-tutorial#76]
### 关于 模块—简介 部分
$ tsc --outFile result.js b.ts
弄好文件之后，我运行了上面的命令，出现如下错误
Cannot compile modules using option 'outFile' unless the '--module' flag is 'amd' or 'system'.
之后我尝试指定值，amd 或 system
结果发现出现的代码无法直接在浏览器运行。
这是一个错误。
如果您认同我的想法，希望尽快改正，感谢您的文档，您的文档yyds

**Comment by ruanyf** [comment]
谢谢指出，这句确实不正确，已经删除了。
