### ISSUE TITLE
typescript 5.0.4 变量定义不赋值不会报错

### ISSUE THREAD

**Issue by Allshadow** [wangdoc/typescript-tutorial#87]
老师，在实操您的 《TypeScript 基本用法》一章，中第一小节类型声明中：TypeScript 规定，变量只有赋值后才能使用，否则就会报错。在typescript 5.0.4版本中没有报错。
![image](https://github.com/wangdoc/typescript-tutorial/assets/39581891/be7ee3f5-6516-478f-9b6c-6da710863647)

**Comment by ruanyf** [comment]
以 TypeScript 官网为准。
