### ISSUE TITLE
【建议】希望增加暗黑模式

### ISSUE THREAD

**Issue by nabaonan** [wangdoc/typescript-tutorial#9]
现在白底晚上看太晃眼了，希望参考一下vue官网那种，可以切换暗黑模式，或者可以实现自动根据时间切换主题

**Comment by ruanyf** [comment]
我后面看看，怎么加暗黑模式。

不过，这个事情的优先级比较低。

**Comment by ruanyf** [comment]
你可以先克隆仓库，用编辑器（比如 VS Code）预览 Markdown 文档。
