### ISSUE TITLE
tsc 命令中的tsc src/*.ts报错

### ISSUE THREAD

**Issue by zhaheng** [wangdoc/typescript-tutorial#90]
```
# 编译 src 目录的所有 .ts 文件
$ tsc src/*.ts
```
tsc src/*.ts这个命令能用吗，我试了使用tsc src/*.ts会报错：

error TS6053: File 'src/*.ts' not found.
  The file is in the program because:
    Root file specified for compilation

**Comment by ruanyf** [comment]
请使用 Bash

**Comment by zhaheng** [comment]
好的
