### ISSUE TITLE
第25章 compilerOptions 拼写问题

### ISSUE THREAD

**Issue by ArisLittle** [wangdoc/typescript-tutorial#92]
阮老师您好。发现2个小拼写问题。

1. compileOptions 少了 r。

https://github.com/wangdoc/typescript-tutorial/blob/f77f8d1b129acab42ac515e8981130ba9281fcab/docs/tsconfig.json.md?plain=1#L159

2. ReadOnly 的 O 似乎应该小写。

https://github.com/wangdoc/typescript-tutorial/blob/f77f8d1b129acab42ac515e8981130ba9281fcab/docs/utility.md?plain=1#L470

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
