### ISSUE TITLE
类型断言章节的句意错误

### ISSUE THREAD

**Issue by everzi** [wangdoc/typescript-tutorial#98]
![image](https://github.com/wangdoc/typescript-tutorial/assets/155417965/cf84a446-6dab-4f37-8f89-7fda4758189e)
loadPerson() 返回不为真，assert()会报错。

**Comment by ruanyf** [comment]
原句不是同一个意思吗？

**Comment by everzi** [comment]
> 原句不是同一个意思吗？

傻了。没理解清楚。老师抱歉
