### ISSUE TITLE
类型系统章节，联合类型小结，书写错误

### ISSUE THREAD

**Issue by lujiuqi** [wangdoc/typescript-tutorial#99]
![图片](https://github.com/wangdoc/typescript-tutorial/assets/44540009/f4d5ce74-3901-4080-90cf-f3efac9d64f6)
联合类型的第一个成员前面没用加 |

**Comment by ruanyf** [comment]
https://wangdoc.com/typescript/types#%E8%81%94%E5%90%88%E7%B1%BB%E5%9E%8B:~:text=%E8%81%94%E5%90%88%E7%B1%BB%E5%9E%8B%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AA%E6%88%90%E5%91%98%E5%89%8D%E9%9D%A2%EF%BC%8C%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%8A%A0%E4%B8%8A%E7%AB%96%E6%9D%A0%7C%EF%BC%8C%E8%BF%99%E6%A0%B7%E4%BE%BF%E4%BA%8E%E5%A4%9A%E8%A1%8C%E4%B9%A6%E5%86%99%E3%80%82

**Comment by ruanyf** [comment]
请问你的截图出自哪个网站？

**Comment by lujiuqi** [comment]
https://typescript.p6p.net/typescript-tutorial/symbol.html这个
